# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
            options={
                'db_table': 'owner',
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(db_index=True, max_length=256)),
                ('address2', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=256, null=True)),
                ('bedrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('home_type', models.CharField(blank=True, max_length=256, null=True)),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('last_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'property',
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(to='vacayo.Property'),
        ),
    ]
