# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0002_property_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/properties'),
        ),
    ]
