# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0003_property_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(related_name='owners', to='vacayo.Property'),
        ),
    ]
