# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0004_auto_20170731_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[(b'pending_review', b'Pending Review'), (b'pending_site_visit', b'Pending Site Visit'), (b'pending_lease_signing', b'Pending Lease Signing')], default=b'pending_review', max_length=256),
        ),
    ]
