# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0005_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[(b'pending_review', b'Pending Review'), (b'pending_site_visit', b'Pending Site Visit'), (b'pending_lease_signing', b'Pending Lease Signing'), (b'ready', b'Ready')], default=b'pending_review', max_length=256),
        ),
    ]
