# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0006_auto_20170801_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('in_service', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zip',
                'verbose_name': 'Zip',
                'verbose_name_plural': 'Zips',
            },
        ),
    ]
