# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0008_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='accepted_agreement_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_radius',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
