# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 02:34
from __future__ import unicode_literals

from django.db import migrations
from vacayo.services.user import UserService
from vacayo.models.owner import Owner


def migrate_owners_into_users(apps, schema_editor):
    user_service = UserService()

    for owner in Owner.objects.all():
        if not owner.user and owner.email:
            user = user_service.get(owner.email)

            if not user:
                user = user_service.create(owner.first_name, owner.last_name, owner.email, None, None)

            owner.user = user
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0010_auto_20171017_0230'),
    ]

    operations = [
        migrations.RunPython(migrate_owners_into_users),
    ]
