# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:51
from __future__ import unicode_literals

from django.db import migrations
from vacayo.services.property import PropertyService
from vacayo.models import Property, Location

def migrate_locations(apps, schema_editor):

    for property in Property.objects.all():
        if not property.location:
            location = Location.objects.create(
                address1=property.address1,
                address2=property.address2,
                city=property.city,
                state=property.state,
                zip_code=property.zip_code
            )

            address = property.address1

            if property.address2:
                address += ' ' + property.address2

            if property.city:
                address += ' ' + property.city

            if property.state:
                address += ' ' + property.state

            if property.zip_code:
                address += ' ' + property.zip_code

            lat, lng = PropertyService().geolocate(address)

            location.latitude = lat
            location.longitude = lng

            location.save()
            property.location = location
            property.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0013_auto_20171027_2016'),
    ]

    operations = [
        migrations.RunPython(migrate_locations),
    ]
