# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0013_auto_20171022_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='manage_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='manage_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='manage_lon',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='manage_radius',
            new_name='radius',
        ),
        migrations.RemoveField(
            model_name='host',
            name='manage_mpoly',
        ),
        migrations.AddField(
            model_name='host',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='property',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
