# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0014_auto_20171024_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='mpoly',
            new_name='geo',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='mpoly',
            new_name='geo',
        ),
    ]
