# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0015_auto_20171027_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacayo.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacayo.Location'),
        ),
    ]
