# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0015_auto_20171024_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lon',
            new_name='longitude',
        ),
    ]
