# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0016_auto_20171027_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacayo.Location')),
            ],
            options={
                'db_table': 'lead',
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
