# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacayo', '0018_auto_20171106_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
