kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: vacayo-ingress
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.global-static-ip-name: vacayo-static-ip
spec:
  tls:
    - secretName: ssl-certs
      hosts:
      - vacayo.com
      - www.vacayo.com
  backend:
    serviceName: vacayo
    servicePort: 80